"use client";
import { authClient } from "@/lib/auth-client";
import { operation } from "@/lib/operations-client";
import { BusFront, CalendarDays, CheckCircle2, ClipboardList, Gauge, LogOut, Plus, RefreshCw, Sparkles, Truck, Users, XCircle } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";

const links = [ ["requests", "Requests", ClipboardList], ["matches", "Shared trips", Sparkles], ["trips", "Trips", CalendarDays], ["vehicles", "Vehicles", BusFront], ["drivers", "Drivers", Users], ["reports", "Reports", Gauge] ];
const input = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 dark:border-slate-700 dark:bg-slate-950";
const button = "rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50";
export default function ManagerOperations({ section = "trips" }) {
  const router = useRouter();
  const { data: session, isPending } = authClient.useSession();
  const [requests, setRequests] = useState([]), [trips, setTrips] = useState([]), [vehicles, setVehicles] = useState([]), [drivers, setDrivers] = useState([]);
  const [selected, setSelected] = useState([]), [vehicleId, setVehicleId] = useState(""), [driverId, setDriverId] = useState(""), [departure, setDeparture] = useState("");
  const [vehicleForm, setVehicleForm] = useState({ name: "", plate: "", seats: "" });
  const [driverForm, setDriverForm] = useState({ name: "", email: "", phone: "" });
  const [reason, setReason] = useState({}), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    try {
      const [r, t, v, d] = await Promise.all([operation("requests"), operation("trips"), operation("vehicles"), operation("drivers")]);
      setRequests(r); setTrips(t); setVehicles(v); setDrivers(d); setError("");
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => {
    if (!isPending && !session) router.replace("/login");
    else if (!isPending && session?.user?.role !== "manager") router.replace("/dashboard/employee");
    else if (session?.user?.role === "manager") { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }
  }, [isPending, session, router, load]);
  const act = async (path, method, body, success) => {
    setBusy(true); setError(""); setNotice("");
    try { await operation(path, { method, body }); setNotice(success); await load(); return true; }
    catch (err) { setError(err.message); return false; }
    finally { setBusy(false); }
  };
  const approved = requests.filter((r) => r.status === "Approved" && !r.tripId);
  const chosen = approved.filter((r) => selected.includes(r.id));
  const canAssign = chosen.length > 0 && chosen.every((r) => r.date === chosen[0].date);
  const tripForm = async (event) => { event.preventDefault(); if (await act("trips", "POST", { requestIds: selected, vehicleId, driverId, departure }, "Trip assigned to driver and employees.")) { setSelected([]); setVehicleId(""); setDriverId(""); setDeparture(""); } };
  if (isPending || !session || session.user.role !== "manager") return <div className="grid min-h-screen place-items-center">Checking your session...</div>;
  return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-white lg:flex">
    <aside className="border-b border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 lg:min-h-screen lg:w-64 lg:border-b-0 lg:border-r"><Link href="/" className="text-xl font-black text-emerald-600">RouteSync</Link><p className="mt-1 text-xs text-slate-500">Transport Manager</p><nav className="mt-7 flex gap-2 overflow-x-auto lg:flex-col">{links.map(([key, label, Icon]) => <Link key={key} href={`/dashboard/manager/${key}`} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${section === key || (section === "overview" && key === "trips") ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-900/30" : "text-slate-600 dark:text-slate-300"}`}><Icon className="size-4" />{label}</Link>)}</nav></aside>
    <main className="mx-auto w-full max-w-7xl p-4 sm:p-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-600">Transport operations</p><h1 className="mt-2 text-3xl font-bold capitalize">{section === "matches" ? "Shared trip assignment" : section === "overview" ? "Trips" : section}</h1><p className="mt-2 text-sm text-slate-500">Review requests, assign drivers and follow trip progress.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border px-3 py-2" aria-label="Refresh"><RefreshCw className="size-4" /></button><button onClick={async () => { await authClient.signOut(); router.replace("/login"); }} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><LogOut className="size-4" />Logout</button></div></header>
      {error && <p role="alert" className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}{notice && <p role="status" className="mt-6 rounded-xl bg-emerald-50 p-4 text-emerald-700">{notice}</p>}
      <div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Pending review", requests.filter((r) => ["Pending", "Priority review"].includes(r.status)).length, ClipboardList], ["Ready to assign", approved.length, CheckCircle2], ["Active trips", trips.filter((t) => !["Completed", "Cancelled"].includes(t.status)).length, Truck]].map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><Icon className="size-5 text-emerald-600" /><p className="mt-3 text-3xl font-bold">{value}</p><p className="text-sm text-slate-500">{label}</p></div>)}</div>
      {loading ? <p className="mt-8">Loading...</p> : <div className="mt-7 space-y-5">
        {section === "requests" && (requests.length ? requests.map((r) => <article key={r.id} className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-emerald-600">{r.id} · {r.employee}</p><h2 className="mt-2 text-lg font-bold">{r.route}</h2><p className="mt-2 text-sm text-slate-500">{r.date} · {r.departure} · {r.passengers} passenger(s) · {r.purpose}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-slate-800">{r.status}</span></div>{r.rejectionReason && <p className="mt-3 text-sm text-rose-600">Reason: {r.rejectionReason}</p>}{r.tripId && <p className="mt-3 text-sm text-emerald-600">Trip: {r.tripId}</p>}{["Pending", "Priority review"].includes(r.status) && <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy} onClick={() => act(`requests/${r.id}/decision`, "PATCH", { status: "Approved" }, `${r.id} approved.`)} className={button}>Approve</button><input value={reason[r.id] || ""} onChange={(event) => setReason((old) => ({ ...old, [r.id]: event.target.value }))} placeholder="Reason for rejection" className={`${input} max-w-xs`} /><button disabled={busy || !reason[r.id]?.trim()} onClick={() => act(`requests/${r.id}/decision`, "PATCH", { status: "Rejected", reason: reason[r.id] }, `${r.id} rejected.`)} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Reject</button></div>}</article>) : <p className="rounded-2xl bg-white p-6 dark:bg-slate-900">No requests yet.</p>)}
        {section === "matches" && <><form onSubmit={tripForm} className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">Create a shared trip</h2><p className="mt-2 text-sm text-slate-500">Select approved requests for the same date. Check their routes and departure times before grouping them.</p><div className="mt-4 space-y-2">{approved.length ? approved.map((r) => <label key={r.id} className="flex items-center gap-3 rounded-xl border p-3 text-sm dark:border-slate-700"><input type="checkbox" checked={selected.includes(r.id)} onChange={() => setSelected((old) => old.includes(r.id) ? old.filter((id) => id !== r.id) : [...old, r.id])} /> <span><b>{r.id}</b> · {r.employee} · {r.route} · {r.date} {r.departure} · {r.passengers} seat(s)</span></label>) : <p>No approved requests waiting for assignment.</p>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><select required value={vehicleId} onChange={(event) => setVehicleId(event.target.value)} className={input}><option value="">Select vehicle</option>{vehicles.map((v) => <option key={v.id} value={v.id}>{v.name} · {v.plate} ({v.seats} seats)</option>)}</select><select required value={driverId} onChange={(event) => setDriverId(event.target.value)} className={input}><option value="">Select driver</option>{drivers.map((d) => <option key={d.id} value={d.id}>{d.name} · {d.email}</option>)}</select><input value={departure} onChange={(event) => setDeparture(event.target.value)} placeholder="Departure time (optional)" className={input} /></div><button disabled={busy || !canAssign} className={`${button} mt-4`}>Assign vehicle and driver</button>{selected.length > 1 && !canAssign && <p className="mt-2 text-sm text-rose-600">Choose requests on the same date.</p>}</form></>}
        {(section === "trips" || section === "overview") && (trips.length ? trips.map((t) => <article key={t.id} className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between gap-3"><b>{t.id}</b><span className="text-emerald-600">{t.status}</span></div><h2 className="mt-3 font-bold">{t.route}</h2><p className="mt-2 text-sm text-slate-500">{t.date} · {t.departure} · {t.vehicle} ({t.plate}) · Driver: {t.driver} · {t.passengers} passenger(s)</p><p className="mt-2 text-xs text-slate-400">Requests: {t.requestIds.join(", ")}</p></article>) : <p className="rounded-2xl bg-white p-6 dark:bg-slate-900">No trips yet. Approve a request and assign it under Shared trips.</p>)}
        {section === "vehicles" && <><form onSubmit={async (e) => { e.preventDefault(); if (await act("vehicles", "POST", vehicleForm, "Vehicle added.")) setVehicleForm({ name: "", plate: "", seats: "" }); }} className="grid gap-3 rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-4"><input required placeholder="Vehicle name" value={vehicleForm.name} onChange={(e) => setVehicleForm({ ...vehicleForm, name: e.target.value })} className={input}/><input required placeholder="Plate number" value={vehicleForm.plate} onChange={(e) => setVehicleForm({ ...vehicleForm, plate: e.target.value })} className={input}/><input required type="number" min="1" placeholder="Seats" value={vehicleForm.seats} onChange={(e) => setVehicleForm({ ...vehicleForm, seats: e.target.value })} className={input}/><button disabled={busy} className={button}>Add vehicle</button></form>{vehicles.map((v) => <p key={v.id} className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900">{v.name} · {v.plate} · {v.seats} seats</p>)}</>}
        {section === "drivers" && <><form onSubmit={async (e) => { e.preventDefault(); if (await act("drivers", "POST", driverForm, "Driver added.")) setDriverForm({ name: "", email: "", phone: "" }); }} className="grid gap-3 rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-4"><input required placeholder="Driver name" value={driverForm.name} onChange={(e) => setDriverForm({ ...driverForm, name: e.target.value })} className={input}/><input required type="email" placeholder="Driver login email" value={driverForm.email} onChange={(e) => setDriverForm({ ...driverForm, email: e.target.value })} className={input}/><input required placeholder="Phone" value={driverForm.phone} onChange={(e) => setDriverForm({ ...driverForm, phone: e.target.value })} className={input}/><button disabled={busy} className={button}>Add driver</button></form><p className="text-sm text-slate-500">Driver must already have a Better Auth account with the driver role.</p>{drivers.map((d) => <p key={d.id} className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900">{d.name} · {d.email} · {d.phone}</p>)}</>}
        {section === "reports" && <div className="rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Live operational summary</h2><p className="mt-3 text-sm">Total requests: {requests.length} · Completed trips: {trips.filter((t) => t.status === "Completed").length} · Assigned passengers: {trips.reduce((sum, t) => sum + t.passengers, 0)}</p></div>}
      </div>}
    </main></div>;
}
